# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a36d6abc72b1015fec2f9f9f6c8892d0e1e89fd56f23b0e52599f4ecba6d7f2eb02672e44d4b0eb2859c7ee0ae3fb3d4876225c951f8ae188d4342e7c42e0134

test:
  secret_key_base: dc85b78e97eab02931c98c25c85366fe3bb85c42c4d3b90c5cccbf934d1faa4fa5ff53feac90ce4d0949e5fa72cbb2466e4ad328a217a26ea92674f73a03ca08

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
